version: "3"

services:
    lint:
        image: namely/protoc-all:1.33_0
        volumes:
            - .:/defs
        entrypoint: "sh -c"
        command: '"protoc -I/usr/local/include -I. --lint_out=. ./post/*.proto; protoc -I/usr/local/include -I. --lint_out=. ./user/*.proto"'
    go_post:
        image: namely/protoc-all:1.33_0
        volumes:
            - .:/defs
        command: "-d ./post -o ./postservice_go --with-docs markdown,readme.md -l go"
    go_user:
        image: namely/protoc-all:1.33_0
        volumes:
            - .:/defs
        command: "-d ./user -o ./userservice_go --with-docs markdown,readme.md -l go"
    ts_post:
        image: namely/protoc-all:1.33_0
        volumes:
            - .:/defs
        command: "-d ./post -o ./postservice_ts --with-docs markdown,readme.md -l web"
    ts_user:
        image: namely/protoc-all:1.33_0
        volumes:
            - .:/defs
        command: "-d ./user -o ./userservice_ts --with-docs markdown,readme.md -l web"