# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1
# Use a package of configuration called an orb.
references:
  defaults: &defaults
    working_directory: ~/grpc-gen
    machine: true

jobs:
  lint:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Lint
          command: docker-compose run --rm lint
      - persist_to_workspace:
          root: .
          paths:
            - .
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Clean up
          command: rm -rf postservice_go userservice_go postservice_ts userservice_ts
      - run:
          name: Check dir
          command: ls
      - run:
          name: Generate post gRPC Code for go
          command: docker-compose run --rm go_post
      - run:
          name: Generate post gRPC Code for typescript
          command: docker-compose run --rm ts_post
      - persist_to_workspace:
          root: .
          paths:
            - .
  push:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: git config
          command: |
            git config user.email "faliplvsg@gmail.com"
            git config user.name "Generator Bot"
            git remote add upstream https://${GITHUB_TOKEN}@github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}.git

      - run:
          name: git commit go-src
          command: |
            if [ `git branch -r --list origin/develop | wc -l` -eq 1 ]; then
              echo "checkout develop"
              git fetch origin
              echo 61
              git worktree add -b postservice_go/* ../go-src origin/develop
              echo 63
              git -C ../go-src rm `git -C ../go-src ls-files`
            else
              echo "create develop"
              git worktree add --detach ../go-src
              git -C ../go-src checkout --orphan develop
              git -C ../go-src rm --cached -r .
              git -C ../go-src clean -d -f
            fi
            echo 71
            cp -a postservice_go/* ../go-src/
            git -C ../go-src add -A
            git -C ../go-src status
            result=0
            echo 76
            git -C ../go-src commit -m "AUTO GENERATED [ci skip]" || result=$?
            echo result
            echo $result
            if [ $result -eq 0 ]; then
              git -C ../go-src push upstream develop 2> /dev/null
            fi
# Orchestrate or schedule a set of jobs
workflows:
  version: 2
  build_and_push:
    jobs:
    - lint
    - build:
        requires:
          - lint
        # filters:
        #   branches:
        #     only:
        #       - master
    - push:
        requires:
          - lint
          - build
        # filters:
        #   branches:
        #     only:
        #       - master